#!/bin/bash
cmake -Bbuild -H. -GNinja -DLIMA_ENABLE_PYTHON=1 -DCAMERA_ENABLE_TESTS=1 -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_FIND_ROOT_PATH=$PREFIX -DLIMA_ENABLE_NUMA=1
cmake --build build --target install
