# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}

package:
  name: lima-camera-slsdetector
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - sip >=4.19.20* # API v12.7
    - lima-core 1.10.*
    - libnuma
    - libpng
    - zeromq
  build:
    - git
    - cmake
    - ninja
    - {{ compiler('cxx') }}
  run:
    - python {{ python }}
    - {{ pin_compatible('sip', min_pin='x.x.x', max_pin='x') }}
    - libnuma
    - libpng
    - zeromq
    - {{ pin_compatible('lima-core', max_pin='x.x') }}

test:
  requires:
    - cmake
  imports:
    - Lima.SlsDetector
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
